name: test

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - uses: extractions/setup-just@v3

      - run: uv python install 3.13

      - run: uv sync --group dev

      - run: just test
